server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/notification
    username: zim4ik
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672
    listener:
      simple:
        observation-enabled: true
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1s
          multiplier: 2
          max-interval: 10s
  profiles:
    active: default
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

rabbitmq:
  exchanges:
    internal: internal.exchange
    dead-letter: internal.dlx
  queues:
    notification: notification.queue
    notification-dead-letter: notification.queue.dlq
  routing-keys:
    internal-notification: internal.notification.routing-key

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
