server:
  port: 8081

spring:
  application:
    name: fraud
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
